### ISSUE TITLE
Error with the VT API: 'data'

### ISSUE THREAD

**Issue by XiQshoner** [fr0gger/vthunting#1]
Hello Folks,

This script looks awesome and I am trying to test it out. However, when I run it I am getting the below error:

so-@ir01:~/vthunting$ sudo python -s vthunting.py 

    __     _______   _   _             _   _
    \ \   / /_   _| | | | |_   _ _ __ | |_(_)_ __   __ _
     \ \ / /  | |   | |_| | | | | '_ \| __| | '_ \ / _` |
      \ V /   | |   |  _  | |_| | | | | |_| | | | | (_| |
       \_/    |_|   |_| |_|\__,_|_| |_|\__|_|_| |_|\__, |
                                                    |___/
        
                 ATR | Thomas Roccia | @fr0gger_
        Get latest hunting notification from VirusTotal

[!] Error with the VT API: 'data'

Thanks,
Eddie

**Comment by fr0gger** [comment]
Hi Eddie, you need to add your VirusTotal Intelligence API in the config part. Please note that it is not working without the VTI api.

**Comment by XiQshoner** [comment]
Does this have to be a paid subscription to VT? The only reason I ask is I
have provided the VT API key in the config.

**Comment by fr0gger** [comment]
Yes the VTI is not free unfortunately, sorry about that! The free API cannot be used with this tool. :(

**Comment by XiQshoner** [comment]
Thanks for the clarification. Nothing more to see here.
