### ISSUE TITLE
Enhancement - JSON Output

### ISSUE THREAD

**Issue by dfirence** [fr0gger/vthunting#5]
Implement a flag like “—to-json” to pull as json structure and integrate into collections based databases TinyDB, MongoDB, Elasticsearch. This allows analysits to add this tool to our toolkits for integrations into our toolkits.

For example, if this available, the CRON JOBS will be json files that are easy to PIPE to JQ. 

Nice work fr0gger_

**Comment by fr0gger** [comment]
option --json implemented :)
